# Base image for project. The idea is that this one does not change 
# very often.

# Use pre-packaged base box from internal registry
FROM docker-internal.tangentuk.local/tangent-12.04:latest

# Set locale information correctly as it can have adverse effects on software
# inside the container
RUN locale-gen en_GB.UTF-8
ENV LANG "en_GB.UTF-8"
ENV LANGUAGE "en_GB.UTF-8"
ENV LC_ALL "en_GB.UTF-8"

RUN apt-get update
RUN apt-get install -y build-essential libfreetype6-dev libjpeg-dev \
    libpng12-dev libxml2-dev libxslt-dev nginx python-dev python-pip \
    supervisor vim zlib1g-dev
RUN apt-get clean && apt-get autoclean
RUN pip install -U pip

############# Tangent Machine User SSH Key ################
# In most instances the machine-user SSH key is required  #
# to pull dependancies from Github or Tangent-Git.        #
#                                                         #
# machine_user.key should NEVER be committed to the repo  #
# copy it manually in place, or symlink it to a file      #
# outside of the working directory before building        #
#                                                         #
###########################################################
#ADD deploy/shared/machine_ssh.key /root/.ssh/id_rsa

# Install Python deps
ADD deploy/shared/requirements.txt /opt/requirements.txt
RUN pip install -r /opt/requirements.txt
