# Best to extend a tagged release of the base box (not latest)
FROM boilerplate-base:latest

# Add codebase
ADD www /var/www

# Add a supervisor script that will run our app and supporting
# services
ADD deploy/supervisor/app.conf /etc/supervisor/conf.d/

# Add our Docker start-up script and make it executable
ADD deploy/docker/start_webserver.sh /opt/start_webserver.sh
RUN chmod +x /opt/start_webserver.sh

# uWSGI is configured to talk WSGI protocol and bind to port 80 by default.
# Nginx should use "uwsgi_pass" to send traffic to it.
EXPOSE 80

# Default command to run. Note that this script requires several environmental
# variables to be passed in order for it to run. On an VM, use something like:
#
# docker run -P \
#   -v /containers/$PROJECT/host/:/host/ \
#   -e DJANGO_CONFIG_URI=/var/www/conf/test.py \
#   $IMAGE_NAME
#
# To run on AWS, use:
# 
# docker run -P \
#   -v /containers/$PROJECT/host/:/host/ \
#   -e DJANGO_CONFIG_URI=s3://$PROJECT/config/prod.py \
#   $IMAGE_NAME
 
CMD ["/opt/start_webserver.sh"]
