# TODO Extend the appropriate base image for this project
FROM boilerplate-base:latest

# Add codebase
ADD www /var/www

# Deploy a supervisor script that will run our app and supporting
# services
ADD deploy/supervisor/app.conf /etc/supervisor/conf.d/

# Add the Docker start-up script and make it executable
ADD deploy/docker/start_webserver.sh /opt/start_webserver.sh
RUN chmod +x /opt/start_webserver.sh

# uWSGI is configured to talk WSGI protocol and bind to port 80 by default.
# Nginx should use "uwsgi_pass" to send traffic to it.
EXPOSE 80

# Default command to run. Note that this script requires several environmental
# variables to be passed in order for it to run. 
#
# Locally, use:
#
#     docker run -P \
#       -v /tmp/:/host/ \
#       -e DJANGO_ENV_URI=/var/www/env/local \
#       $IMAGE_NAME
#
# On a (non-AWS) VM, use:
#
#     docker run -P \
#       -v /containers/$PROJECT/:/host/ \
#       -e DJANGO_ENV_URI=/host/env/test \
#       $IMAGE_NAME
#
# To run on an AWS EC2, use:
# 
#     docker run -P \
#       -v /containers/$PROJECT/:/host/ \
#       -e DJANGO_ENV_URI=s3://$PROJECT/env/prod \
#       $IMAGE_NAME
 
CMD ["/opt/start_webserver.sh"]
